//https://api.github.com/users/thuy-n3?access_token=

login: "thuy-n3",
id: 16273805,
avatar_url: "https://avatars.githubusercontent.com/u/16273805?v=3",
gravatar_id: "",
url: "https://api.github.com/users/thuy-n3",
html_url: "https://github.com/thuy-n3",
followers_url: "https://api.github.com/users/thuy-n3/followers",
following_url: "https://api.github.com/users/thuy-n3/following{/other_user}",
gists_url: "https://api.github.com/users/thuy-n3/gists{/gist_id}",
starred_url: "https://api.github.com/users/thuy-n3/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/thuy-n3/subscriptions",
organizations_url: "https://api.github.com/users/thuy-n3/orgs",
repos_url: "https://api.github.com/users/thuy-n3/repos",
events_url: "https://api.github.com/users/thuy-n3/events{/privacy}",
received_events_url: "https://api.github.com/users/thuy-n3/received_events",
type: "User",
site_admin: false,
name: "Thuy Nguyen",
company: null,
blog: "https://medium.com/@ms.thuynguyen",
location: "Houston,Texas",
email: "ms.tnguyen3@gmail.com",
hireable: null,
bio: null,
public_repos: 43,
public_gists: 0,
followers: 4,
following: 14,
created_at: "2015-12-13T05:21:59Z",
updated_at: "2016-06-08T01:15:11Z",
private_gists: 0,
total_private_repos: 0,
owned_private_repos: 0,
disk_usage: 34186,
collaborators: 0,
plan: {}